Basic touchscreen support (#147) and minor bugfixes
drawdb-io/drawdb pull request #148
Opened 2024-06-26 20:58 UTC by FelixZY

2024-06-27 09:40 UTC, 1ilit requested changes
Thanks for the contribution. 

When the zoom is anything but 1 the red dashed line for linking fields does not end on the cursor. Could you please check it out?

Other than that everything looks great

2024-06-27 18:44 UTC, FelixZY commented
@1ilit I'll look into it but it will probably be a few days before I'm able.

2024-06-27 19:12 UTC, 1ilit commented
@FelixZY no worries take your time

2024-06-30 22:56 UTC, FelixZY commented
@1ilit Try it out now. I still need to tidy up a bit (`git rebase -i --autosquash main`, write a proper commit message on the last commit, figure out what to do with my type declarations) but the code should be reviewable from a functionality standpoint.

For the future: please consider migrating to Typescript.

2024-07-12 18:08 UTC, FelixZY commented
@1ilit the branch is now cleaned up, rebased and ready to review, test and merge!

2024-07-13 11:12 UTC, FelixZY commented
I added a jitter fix as well. It's based on @l123wx's fix in #93 but less intrusive and hopefully more easily understood.

2024-07-14 13:50 UTC, FelixZY commented
Rebased on main and added scroll wheel panning. I'm not planning on adding more features :sweat_smile:

2024-07-16 18:12 UTC, newpgit commented
> Rebased on main and added scroll wheel panning. I'm not planning on adding more features :sweat_smile: 

Hello, I tried the tablet movement sensitivity is very high, move a little bit of view to move a large distance, if you can add double finger zoom

你好，我试了一下 平板移动灵敏度很高，移动一点点视图就移动很大的距离，如果可以的话可以加上双指缩放吗

2024-07-16 18:33 UTC, newpgit commented
> Rebased on main and added scroll wheel panning. I'm not planning on adding more features 😅


https://github.com/user-attachments/assets/ad4895e2-0a14-4a5e-b193-bc44f8ae4317

2024-07-16 18:46 UTC, FelixZY commented
@newpgit I have not added support for gestures at this time - though I'm considering doing so after this PR has been accepted. Zoom gestures should not be working at this time.

> the tablet movement sensitivity is very high, move a little bit of view to move a large distance

What type of interaction are you referring to? The screencast is really appreciated! However, I'm unable to see your touch points and am therefore unable to infer your intended actions. Are you experiencing that the view is moving faster than you are panning?

2024-07-17 05:55 UTC, newpgit commented
> @newpgit I have not added support for gestures at this time - though I'm considering doing so after this PR has been accepted. Zoom gestures should not be working at this time.
> 
> > the tablet movement sensitivity is very high, move a little bit of view to move a large distance
> 
> What type of interaction are you referring to? The screencast is really appreciated! However, I'm unable to see your touch points and am therefore unable to infer your intended actions. Are you experiencing that the view is moving faster than you are panning?

Sorry, the previous video indeed didn't show the issue. Here's a new recording I've made.

https://github.com/user-attachments/assets/bab6f179-386f-466a-a023-d5b976acae7f

2024-07-17 07:53 UTC, FelixZY commented
@newpgit thank you very much - that is indeed strange. I'll take a look soon.

2024-07-17 08:28 UTC, newpgit commented
> @newpgit thank you very much - that is indeed strange. I'll take a look soon.

ok😄

2024-07-17 08:28 UTC, FelixZY commented
@newpgit I have tested the following:
* Google Chrome on Linux Desktop (with and without touch emulation) (Chromium/Blink)
* Firefox on Linux Desktop (with and without touch emulation) (Gecko)
* [GNOME Web/Epiphany](https://flathub.org/apps/org.gnome.Epiphany) on Linux Desktop (WebKit)
* Google Chrome on android 14 tablet (with touch and stylus)
* Firefox on android 14 tablet (with touch and stylus)
* Microsoft Edge on android 14 tablet (with touch and stylus)

Unfortunately, I'm unable to reproduce your results.

It looks like you are using an iPad in the recording - unfortunately I do not have access to one. I have seen from previous issues (e.g. #46 and #47) that safari has (for quite some time!) some issues with rendering things in the correct position (https://bugs.webkit.org/show_bug.cgi?id=23113). I can't say for sure that's what you are running into but that could be a possible explanation.

What I do see in your video is that the viewbox itself appears to change size as you move tables around - that definitely should not happen (and indeed does not on my devices).

2024-07-17 08:44 UTC, newpgit commented
> @newpgit I have tested the following:
> 
> * Google Chrome on Linux Desktop (with and without touch emulation) (Chromium/Blink)
> * Firefox on Linux Desktop (with and without touch emulation) (Gecko)
> * [GNOME Web/Epiphany](https://flathub.org/apps/org.gnome.Epiphany) on Linux Desktop (WebKit)
> * Google Chrome on android 14 tablet (with touch and stylus)
> * Firefox on android 14 tablet (with touch and stylus)
> * Microsoft Edge on android 14 tablet (with touch and stylus)
> 
> Unfortunately, I'm unable to reproduce your results.
> 
> It looks like you are using an iPad in the recording - unfortunately I do not have access to one. I have seen from previous issues (e.g. #46 and #47) that safari has (for quite some time!) some issues with rendering things in the correct position (https://bugs.webkit.org/show_bug.cgi?id=23113). I can't say for sure that's what you are running into but that could be a possible explanation.
> 
> What I do see in your video is that the viewbox itself appears to change size as you move tables around - that definitely should not happen (and indeed does not on my devices).

Yes, I have no problem using my phone. It seems like only the iPad has this issue.

2024-07-17 18:30 UTC, 1ilit requested changes
Great work! Love the new additions. Just a couple of few edits that should be done.

In addition to the comments, connecting the columns on mobile doesn't seem to work. Could you please check that out as well?

https://github.com/user-attachments/assets/4ec32c65-273a-4812-822e-6b68e62aebde

If you have any questions or objects don't hesitate to reach out.

Thank you:)

2024-07-17 18:30 UTC, 1ilit commented on src/components/EditorHeader/ControlPanel.jsx
With the new changes to the controls for zoom please update the shortcuts to "Ctrl+Wheel" on lines 1200 and 1204 in addition to updating `./src/data/shortcuts.js`. I'd also appreciate if you added the controls for horizontal and vertical pan to `./src/data/shortcuts.js`.

2024-07-17 18:30 UTC, 1ilit commented on src/context/TransformContext.jsx
>  export const TransformContext = createContext(null);
The null default value results in a ts-check error (Property 'transform' does not exist on type 'null'.) on `transform` in `CanvasContext.js`. Please provide a non null default value if you decide to keep CanvasContext.js.

2024-07-17 18:30 UTC, 1ilit commented on src/components/EditorCanvas/Canvas.jsx
> +const CanvasContext = createContext(null);
Duplicate

2024-07-17 18:30 UTC, 1ilit commented on src/context/CanvasContext.js
When defining the context could you please stick to the already existing pattern? This involves having the `CanvasContext.jsx` file create the context and a `CanvasContext.Provider` wrapper with all the necessary logic. Then you can define the `useCanvas` hook in the hooks directory that actually consumes and returns that value of the provider.

2024-07-17 18:30 UTC, 1ilit commented on src/context/CanvasContext.js
> +export function useCanvasContextProviderValue(canvasRef) {
The name is a bit misleading. I would assume it consumes and returns the value from the context provider but it returns an object generated based on a ref.

2024-07-17 18:45 UTC, FelixZY commented on src/context/TransformContext.jsx
>  export const TransformContext = createContext(null);
This comment is in `TransformContext` where I have not changed the default value in `createContext`. In `CanvasContext.js` I actually do provide a default value so I'm not sure what you want me to do here.

2024-07-17 18:47 UTC, FelixZY commented on src/context/TransformContext.jsx
>  export const TransformContext = createContext(null);
Wait, you are referring to the `Property 'transform' does not exist on type 'null'.` warning which is raised on line 40 of `CanvasContext.js`:

```
const { transform } = useTransform();
```

The easiest thing to do would be to simply remove `//@ts-check` at the top of the file which would suppress this error (and other useful ones). Would you like me to do this?

2024-07-17 18:57 UTC, FelixZY commented on src/context/CanvasContext.js
I can but I don't really like this pattern. IMO, the context originates with the canvas and therefore, adding a `<Canvas>` element should automatically include a `<CanvasContext.Provider>`. It's a bit strange for the canvas to depend on "its own" context.

Also, wrapping all your code with `Context` can lead to performance issues (see e.g. #154 ).

2024-07-17 19:04 UTC, FelixZY commented on src/context/CanvasContext.js
> +export function useCanvasContextProviderValue(canvasRef) {
I think the name describes the intent of the function acceptably (see also [my previous response](https://github.com/drawdb-io/drawdb/pull/148#discussion_r1681584836)).

This function returns the value that the caller needs to pass to `<CanvasContext.Provider value={here}>`.

Note that I'm actively and knowling breaking the pattern previously established (e.g. `useTransfom`/`useDiagram`/`useAreas`) and therefore appending the rather verbose `ProviderValue` suffix as a way to differentiate. If I wanted to do this:

> I would assume it consumes and returns the value from the context provider

I would name the function `useCanvas`

2024-07-17 19:06 UTC, FelixZY commented on src/components/EditorHeader/ControlPanel.jsx
Fixed

2024-07-17 19:06 UTC, FelixZY commented on src/components/EditorCanvas/Canvas.jsx
> +const CanvasContext = createContext(null);
Fixed

2024-07-17 19:15 UTC, FelixZY commented on src/components/EditorCanvas/Table.jsx
> +        onPointerEnter={(e) => {
Seems like `onPointerEnter` does not trigger in the same way when using non-mouse pointers

2024-07-17 19:24 UTC, 1ilit commented on src/context/CanvasContext.js
The canvas provider wrapper would only wrap the canvas element not the whole workspace. The point is to separate the logic for handling the values that would later be consumed. I do get what you're saying but the js file in all the jsx files kinda irks me.

2024-07-17 19:32 UTC, 1ilit commented on src/context/TransformContext.jsx
>  export const TransformContext = createContext(null);
Yep

2024-07-17 19:33 UTC, FelixZY commented on src/components/EditorCanvas/Table.jsx
> +        onPointerEnter={(e) => {
Fixed

2024-07-17 19:34 UTC, FelixZY commented on src/context/TransformContext.jsx
>  export const TransformContext = createContext(null);
Fixed

2024-07-17 19:48 UTC, FelixZY commented on src/context/CanvasContext.js
> The point is to separate the logic for handling the values that would later be consumed.

That's fine. However, I think it is better to separate this _logic_ itself (i.e. as I did in `CanvasContext.js` where I exposed a function (`useCanvasContextProviderValue`) rather than a _wrapper_ which requires extra code from the implementor.

Anyways, I have updated the code to follow the established standard.

Fixed.

2024-07-17 19:49 UTC, FelixZY commented on src/context/CanvasContext.js
> +export function useCanvasContextProviderValue(canvasRef) {
Fixed

2024-07-17 20:02 UTC, 1ilit approved these changes

2024-07-17 20:40 UTC, 1ilit approved these changes

2024-07-17 20:42 UTC, merged