added Turkish Language
drawdb-io/drawdb pull request #165
Opened 2024-07-25 12:45 UTC by volkankoc

added Turkish Language

2024-07-25 12:46 UTC, volkankoc commented
please add turkish language

2024-07-25 19:45 UTC, 1ilit requested changes

2024-07-25 19:45 UTC, 1ilit commented on src/i18n/locales/tr.js
> +const english = {
Please rename this to 'turkish'

2024-07-25 20:30 UTC, volkankoc commented on src/i18n/locales/tr.js
> +const english = {
i change it

2024-07-25 20:32 UTC, volkankoc reviewed
I change it

2024-07-26 07:50 UTC, 1ilit approved these changes

2024-07-26 08:15 UTC, merged